// Steven Kochan | Programming in C - Chapter 5 (Program Looping)
// Hadrien Lacroix - 5_ex3_triangularTable.c

/*  A triangular number can also be generated by the formula
    triangularNumber = n (n + 1) / 2
    for any integer value of n.
    
    For example, the 10th triangular number, 55, can be
    generated by substituting 10 as the value for n in the preceding formula
    Write a program that generates a table of triangular numbers using the preceding formula.
    Have the program generate every fifth triangular number between 5 and 50 (that
    is, 5, 10, 15, ..., 50). */


#include <stdio.h>

int main (void)
{
    int n = 5, triangularNumber;
    
    printf("Table of triangular numbers 5 by 5\n");
    printf("----------------------------------\n");
    printf(" n              Triangular numbers\n");
    
    while (n <= 50)
    {
        triangularNumber = n * (n + 1) / 2;
        printf("%2i                      %4i\n", n, triangularNumber);
        n = n + 5;
    }
    
    return 0;
}